name = "threejs-solar-system"

# 指定构建输出目录
[build]
command = "npm install && npm run build"
pages_build_output_dir = "dist"

[env.production]
name = "threejs-solar-system-prod"
route = "" # 需要填入你的域名 

[build.upload]
format = "directory"

[site]
bucket = "./dist"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--platform=linux --arch=x64" 